<a href="https://colab.research.google.com/github/farhann-farooq/Data-Analysis-Journey/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importing Numpy

In [10]:
import numpy as np

### Creating NumPy Array

In [11]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

## Dimensions In Array

#### Zero Dimension Array

In [12]:
zeroArr = np.array(20)
print(zeroArr)
#using ndim to view the dimension of the array}
print(zeroArr.ndim)

20
0


#### 1D Array

In [13]:
oneDarr = np.array([10, 20, 30])
print(oneDarr)
print(oneDarr.ndim)

[10 20 30]
1


### 2D Array

In [14]:
twoDarr = np.array([[10,20,30],[40,50,60]])
print(twoDarr)
print(twoDarr.ndim)

[[10 20 30]
 [40 50 60]]
2


### 3D Array

In [15]:
threeDarr = np.array([[[10, 20, 30],[40, 50, 60]],[[70, 80, 90], [110, 120, 130]]])
print(threeDarr)
print(threeDarr.ndim)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [110 120 130]]]
3


### Higher Dimensional Array

In [16]:
arr = np.array([1,2,3,4,5], ndmin=5)
print(arr)
print("Dimensions of Array: ", arr.ndim)

[[[[[1 2 3 4 5]]]]]
Dimensions of Array:  5


### NumPy Array Indexing

In [17]:
print('Indexing for 1D Array:')
oneDarr = np.array([1, 2, 3, 4, 5])
print(oneDarr[0])

print('Indexing for 2D Array:')
twoDarr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(twoDarr[1,2])

print('Indexing for 3D Array:')
threeDarr = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])
print(threeDarr[1,0,2])

Indexing for 1D Array:
1
Indexing for 2D Array:
8
Indexing for 3D Array:
13


### Adding elements in different dimensional NumPy Array

In [18]:
# Addition in 1D Array
arrOne = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Addition in 1D Array:", arrOne[0] + arrOne[5])

# Addition in 2D Array
arrTwo = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])
print("Addition in 2D Array:", arrTwo[0, 0] + arrTwo[1, 5])

# Addition in 3D Array
arrThree = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])
print("Addition in 3D Array:", arrThree[0, 0, 0] + arrThree[1, 1, 0])

Addition in 1D Array: 7
Addition in 2D Array: 17
Addition in 3D Array: 17


### Slicing in NumPy Array


---

#### 1D Array

In [19]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(x)
print(x[0:5])

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5]


#### 2D Array

In [20]:
y = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(y)
print(y[1, 0:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[6 7 8 9]


#### 3D Array

In [21]:
z = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])
print(z)
print(z[1, 0, 0:4])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
[11 12 13 14]


### Checking the data type of an Array

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr)
print(arr.dtype)

[1 2 3 4 5 6 7]
int64


### Creating array with predefined data type

In [23]:
arr = np.array([1, 2, 3, 4, 5], dtype = 'S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


### Numpy Array Shape


---

The shape of an array is the number of elements in each dimension

In [24]:
# 1D Array
arr1 = np.array([1, 2, 3, 4, 5, 6])
print(arr1.shape)

# 2D Array
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr2.shape)

# 3D Array
arr3 = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])
print(arr3.shape)

(6,)
(2, 5)
(2, 2, 5)


### Joining NumPy Array

In [25]:
# 1D Array
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(np.concatenate((a, b)))

#2D Array
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print(np.concatenate((x, y), axis = 0))

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Splitting Array

In [26]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


### Converting Multidimensional Array Into 1D Array

In [27]:
x = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]])
print(x)
a = x.flatten() # or use x.ravel()
print(a)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
[ 1  2  3  4  5  6  7  8  9 10]


### Unique Function

In [28]:
x = np.array([4, 1, 8, 1, 3, 2, 9, 6, 6, 10, 2, 3, 7, 5, 3, 7, 8, 9, 10])
a = np.unique(x, return_index = True, return_counts = True)
print(a)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array([ 1,  5,  4,  0, 13,  7, 12,  2,  6,  9]), array([2, 2, 3, 1, 1, 2, 2, 2, 2, 2]))


### Delete

In [29]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
a = np.delete(x, 0, axis = 0)
print(a)

[[ 6  7  8  9 10]
 [11 12 13 14 15]]
