<a href="https://colab.research.google.com/github/farhann-farooq/Data-Analysis-Journey/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importing Numpy

In [ ]:
import numpy as np

### Creating NumPy Array

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

## Dimensions In Array

#### Zero Dimension Array

In [ ]:
zeroArr = np.array(20)
print(zeroArr)
#using ndim to view the dimension of the array}
print(zeroArr.ndim)

20
0


#### 1D Array

In [ ]:
oneDarr = np.array([10, 20, 30])
print(oneDarr)
print(oneDarr.ndim)

[10 20 30]
1


### 2D Array

In [ ]:
twoDarr = np.array([[10,20,30],[40,50,60]])
print(twoDarr)
print(twoDarr.ndim)

[[10 20 30]
 [40 50 60]]
2


### 3D Array

In [ ]:
threeDarr = np.array([[[10, 20, 30],[40, 50, 60]],[[70, 80, 90], [110, 120, 130]]])
print(threeDarr)
print(threeDarr.ndim)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [110 120 130]]]
3


### Higher Dimensional Array

In [ ]:
arr = np.array([1,2,3,4,5], ndmin=5)
print(arr)
print("Dimensions of Array: ", arr.ndim)

[[[[[1 2 3 4 5]]]]]
Dimensions of Array:  5


### NumPy Array Indexing

In [ ]:
print('Indexing for 1D Array:')
oneDarr = np.array([1, 2, 3, 4, 5])
print(oneDarr[0])

print('Indexing for 2D Array:')
twoDarr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(twoDarr[1,2])

print('Indexing for 3D Array:')
threeDarr = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])
print(threeDarr[1,0,2])

Indexing for 1D Array:
1
Indexing for 2D Array:
8
Indexing for 3D Array:
13


### Adding elements in different dimensional NumPy Array

In [ ]:
# Addition in 1D Array
arrOne = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Addition in 1D Array:", arrOne[0] + arrOne[5])

# Addition in 2D Array
arrTwo = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])
print("Addition in 2D Array:", arrTwo[0, 0] + arrTwo[1, 5])

# Addition in 3D Array
arrThree = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])
print("Addition in 3D Array:", arrThree[0, 0, 0] + arrThree[1, 1, 0])

Addition in 1D Array: 7
Addition in 2D Array: 17
Addition in 3D Array: 17


### Slicing in NumPy Array